Enrollment number: 240840116049

# **Practical 01: Study the Data Analytics lifecycle and perform data acquisition from CSV,Excel, and JSON files using Pandas.**

**Step1: Importing Library.**

In [66]:
# Import Pandas Library.
import pandas as pd

**Step:2 Create a DataFrame.**

In [67]:
data = {
    "ID" : [101,102,103,104,105,106,107],
    "Name" : ["Rahul", "Priya", "Amit", "Riya", "Karan", "Krish", "Harry"],
    "Age" : [20,21,19,20,22,24,28],
    "City" : ["Surat", "Navsari", " Valsad", "Bharuch", "Surat" , "Gandhinagar", "Ahemdabad"],
    "Marks":  [85,92,78,88,81,84,90]
}

**Step:3 Storing a DataFrame.**

In [68]:
# Store a DataFrame in df variable.
df = pd.DataFrame(data)

**Step:4 Display a DataFrame.**

In [69]:
# Display the pd.DataFrame
df

    ID   Name  Age         City  Marks
0  101  Rahul   20        Surat     85
1  102  Priya   21      Navsari     92
2  103   Amit   19       Valsad     78
3  104   Riya   20      Bharuch     88
4  105  Karan   22        Surat     81
5  106  Krish   24  Gandhinagar     84
6  107  Harry   28    Ahemdabad     90

**Step:5 Data Converting in CSV.**

In [70]:
# Save Data as a CSV File
df.to_csv("student.csv", index=False) # index=False for index value remove
print("CSV file created successfully.") # dor the Display msg CSV file created...

CSV file created successfully.

**Step:6 Data Converting in EXCEL.**

In [71]:
# Save Data as a EXCEL File
df.to_excel("student.xlsx", index=False) # index=False for index value remove
print("EXCEL file created successfully.") # dor the Display msg EXCEL file created...

EXCEL file created successfully.

**Step:7 Data Converting in JSON.**

In [72]:
# Save Data as a JSON File
df.to_json("student.json",orient="records", index=False) #  orinets:- create a list of JSON Objects index=False for index value remove
print("JSON file created successfully.") # dor the Display msg JSON file created...

JSON file created successfully.

**Step:8 Display a DataFrame for CSV.**

In [73]:
# Display a dataframe for the CSV.
df_csv = pd.read_csv("student.csv")
df_csv

    ID   Name  Age         City  Marks
0  101  Rahul   20        Surat     85
1  102  Priya   21      Navsari     92
2  103   Amit   19       Valsad     78
3  104   Riya   20      Bharuch     88
4  105  Karan   22        Surat     81
5  106  Krish   24  Gandhinagar     84
6  107  Harry   28    Ahemdabad     90

**Step:9 Display a DataFrame for EXCEL.**

In [74]:
df_excel = pd.read_excel("student.xlsx")
df_excel

    ID   Name  Age         City  Marks
0  101  Rahul   20        Surat     85
1  102  Priya   21      Navsari     92
2  103   Amit   19       Valsad     78
3  104   Riya   20      Bharuch     88
4  105  Karan   22        Surat     81
5  106  Krish   24  Gandhinagar     84
6  107  Harry   28    Ahemdabad     90

**Step:10 Display a DataFrame for JSON.**

In [75]:
# Display a dataframe for the JSON.
df_json = pd.read_json("student.json")
df_json

    ID   Name  Age         City  Marks
0  101  Rahul   20        Surat     85
1  102  Priya   21      Navsari     92
2  103   Amit   19       Valsad     78
3  104   Riya   20      Bharuch     88
4  105  Karan   22        Surat     81
5  106  Krish   24  Gandhinagar     84
6  107  Harry   28    Ahemdabad     90

**Step:11 Display a first 5 values.**

In [76]:
# Display first 5 data, using head()
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

**Step:12 Display a last 5 values.**

In [77]:
#Display last 5 data, using tail()
df_csv.tail()

    ID   Name  Age         City  Marks
2  103   Amit   19       Valsad     78
3  104   Riya   20      Bharuch     88
4  105  Karan   22        Surat     81
5  106  Krish   24  Gandhinagar     84
6  107  Harry   28    Ahemdabad     90

**Step:13 Display a information about the DataFrame.**

In [78]:
# Display information about the dataframme.
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

**Step:14 Display decriptive statistics.**

In [79]:
# Display decriptive statistics for  numerical colums
df_csv.describe()
# it calculates
# count
# mean
# startdaed devication, minimum , maximum etc.

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

**Step:15 Display the numbers of rows and columns.**

In [80]:
# Display the
df_csv.shape
# return a tuple,

(7, 5)

**Step:16 Display the columns list.**

In [81]:
# Display column names for the name of columns.
df_csv.columns
# return rhe name of all columns in the dat aframer

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

**Step:17 Diplay the data types of each column**

In [82]:
# Diplay the all data types of each column
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

**Step:18 Missing values.**

In [83]:
# Count the missing values each column.
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

**Step:19 Display only the "marks" column.**

In [84]:
# Display specific only the "marks" column.
df_csv["Marks"]
# select an d display one specific column from the dataframe

0    85
1    92
2    78
3    88
4    81
5    84
6    90
Name: Marks, dtype: int64

**Step:20 Display the two columns 'Name' and 'Marks' columns.**

In [85]:
# Display the 'Name' and 'Marks' colums.
df_csv[["Name", "Marks"]]

    Name  Marks
0  Rahul     85
1  Priya     92
2   Amit     78
3   Riya     88
4  Karan     81
5  Krish     84
6  Harry     90

**Step:21 Students whose marks are greater than 80.**

In [86]:
# Students whose marks are greater than 80.

df_csv[df_csv["Marks"]>80]
# [df_csv["Marks"]>80]create a boolean condition.

    ID   Name  Age         City  Marks
0  101  Rahul   20        Surat     85
1  102  Priya   21      Navsari     92
3  104   Riya   20      Bharuch     88
4  105  Karan   22        Surat     81
5  106  Krish   24  Gandhinagar     84
6  107  Harry   28    Ahemdabad     90

**Step:22 Calculate the average marks.**

In [87]:
#Calculate the average of the 'marks' column
df_csv["Marks"].mean()
#mean() computes the arithmetoc average og the seledcted column,

np.float64(85.42857142857143)

**Step:23 Sorting columns.**

In [88]:
# Sort the datframe in descending order of marks.
df_csv.sort_values(by="Marks", ascending=False)
# sort_values() sorts the dataframe

    ID   Name  Age         City  Marks
1  102  Priya   21      Navsari     92
6  107  Harry   28    Ahemdabad     90
3  104   Riya   20      Bharuch     88
0  101  Rahul   20        Surat     85
5  106  Krish   24  Gandhinagar     84
4  105  Karan   22        Surat     81
2  103   Amit   19       Valsad     78

**Step:24 display the final dataframe.**

In [89]:
# Final dataframe.
print(df_csv)

    ID   Name  Age         City  Marks
0  101  Rahul   20        Surat     85
1  102  Priya   21      Navsari     92
2  103   Amit   19       Valsad     78
3  104   Riya   20      Bharuch     88
4  105  Karan   22        Surat     81
5  106  Krish   24  Gandhinagar     84
6  107  Harry   28    Ahemdabad     90